// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6x2hI9LUq2CzydyDJHqiZHxmB7mjCD9o',
    appId: '1:765869835430:web:9890c2cced3d54f1dce067',
    messagingSenderId: '765869835430',
    projectId: 'ecommerce-f72b3',
    authDomain: 'ecommerce-f72b3.firebaseapp.com',
    databaseURL: 'https://ecommerce-f72b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-f72b3.firebasestorage.app',
    measurementId: 'G-1X4T1D4FHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIItq7c19MFsxxkE58bM6K4GokZlwwj4w',
    appId: '1:765869835430:android:cee9e4e557600d58dce067',
    messagingSenderId: '765869835430',
    projectId: 'ecommerce-f72b3',
    databaseURL: 'https://ecommerce-f72b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-f72b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6x2hI9LUq2CzydyDJHqiZHxmB7mjCD9o',
    appId: '1:765869835430:web:137743dd6a6ba424dce067',
    messagingSenderId: '765869835430',
    projectId: 'ecommerce-f72b3',
    authDomain: 'ecommerce-f72b3.firebaseapp.com',
    databaseURL: 'https://ecommerce-f72b3-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-f72b3.firebasestorage.app',
    measurementId: 'G-DR77TKB9GR',
  );
}
