import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart'; // Required for CartModel

import 'firebase_options.dart'; // Auto-generated by flutterfire configure
import 'sign_in_screen.dart';
import 'home_screen.dart';
import 'special_offers_screen.dart';
import 'notifications_screen.dart';
import 'cart_model.dart'; // Import CartModel
import 'my_cart_screen.dart'; // Import MyCartScreen
import 'checkout_screen.dart'; // Import CheckoutScreen
import 'order_confirmation_screen.dart'; // Import OrderConfirmationScreen
import 'order_tracking_screen.dart'; // Import OrderTrackingScreen
import 'delivery_boy_screen.dart'; // <--- NEW: Import DeliveryBoyScreen


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    // Wrap the entire app with ChangeNotifierProvider to make CartModel available
    ChangeNotifierProvider(
      create: (context) => CartModel(), // Provide an instance of CartModel
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Google Sign-In App',
      theme: ThemeData(primarySwatch: Colors.blue),
      initialRoute: '/',
      routes: {
        '/': (context) => const SignInScreen(),
        '/home': (_) => const HomeScreen(),
        '/special_offers': (_) => const SpecialOffersScreen(),
        '/notifications': (_) => const NotificationsScreen(),
        '/my_cart': (_) => const MyCartScreen(),
        '/checkout': (_) => const CheckoutScreen(),
        '/order_confirmation': (_) => const OrderConfirmationScreen(),
        '/order_tracking': (_) => const OrderTrackingScreen(),
        // Define DeliveryBoyScreen route. Pass a default riderId for demonstration.
        '/delivery_boy': (context) => const DeliveryBoyScreen(riderId: 'rider_001'), // <--- NEW: Add route for DeliveryBoyScreen
      },
    );
  }
}
